### ISSUE TITLE
Configure tests

### ISSUE THREAD

**Issue by Synchro** [Synchro/laravel-medialibrary-audio#1]
This project contains just a simple plugin, but in order to test it, it's necessary to bootstrap and configure an entire Laravel instance with an installation of Spatie Media Library. The only reason this is needed is because the FFmpeg instance the plugin uses needs to know the paths to the ffmpeg and ffprobe binaries, and these are obtained from the ML config, and access to that config is handled via Laravel's `config` helper function, which can't work unless there is an `app` instance, and so on, until you have a fully shaved yak.

The tests are very simple, but they have huge config implications, and I'm just not sure where to start.

**Comment by Gummibeer** [comment]
You should `require-dev` the orchestra testbench and the base medialibrary package.
I will see if I can PR something.
