### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by jayenne** [Synchro/laravel-medialibrary-audio#4]
Hi, I've just been pointed here by Spatie and don't really know how to install it as it's not a package. would you have any short instructions? (the Spatie page for `Creating a custom image generator` doesn't say either and I'd hate to be getting it all wrong.

thanks.

**Comment by jayenne** [comment]
DOH! ... I've just found it on packagist lol. #idiotMe

**Comment by Synchro** [comment]
This was a silly omission by me, so I've extended the instructions to include that. Thanks for the report and I hope it works well for you.

**Comment by jayenne** [comment]
I'm sure it does. thank you.
could i be cheeky and tap your knowledge on an error i'm getting please?
I've installed: `composer require php-ffmpeg/php-ffmpeg;`
then it get a fail on:
`FFMpeg\Exception\ExecutableNotFoundException Unable to load FFProbe at vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php:50`

**Comment by Synchro** [comment]
You need to set the paths to ffmpeg and ffprobe explicitly in the media-library config file or in your .env. It seems it's not very good at finding them automatically.

**Comment by jayenne** [comment]
Thanks for that help Synchro.

As i'm using Laravel Sail, and as others may find it helpful, ...I also needed to install ffpmeg via my docker file. This is how i did it...

Firstly: Test if Sail has ffmpeg alread... `sail up -d && sail shell` then type `ffmpeg` return. it'll let you know if ffmpeg is installed here.

If not (it's not in the default sail).... 

Ensure Sail is down: `sail down --remove-orphans`
Publish Sail's docker file: `sail artisan sail:publish`
now, insert a new line within `docker/8.0/dockerfile` and inster this:`&& apt-get install -y ffmpeg \` after `& apt-get install -y postgresql-client \` then save it.
Finally, rebuild Sail with: `sail build --no-cache && sail up -d`.
and all sohuld be good.

*if there is another way to get ffmpeg working on sail without publishing/editing the dockerfile then i'd love to know it.

Thanks for all you help Syncro.
