### ISSUE TITLE
possible transparent background

### ISSUE THREAD

**Issue by jayenne** [Synchro/laravel-medialibrary-audio#9]
hI again,
your code generates an image then reloads it to add a background colour. would it be possible to not force background colour and instead, set background as nullable, then if no background colour is given, skip the add `background color` process?

I ask because I would like to use the waveform as an overlay and although could use a css mix-blend mode I think there are probably more cases where a transparent background is more desirable.

thanks.

**Comment by Synchro** [comment]
That's possible - the image that comes back from FFMpeg is transparent, however I don't think it's a great idea for a default. Browsers may often not count transparent areas as clickable, and quiet audio files can end up as very thin lines. I also have no idea if MLP deals with transparent images properly.

Being able to overlay a background image would be cool though. As I say in #3, FFMpeg doesn't let you get your hands on the internal representation of the image, so you have little choice but to write it out and read it back in. The current implementation is limited by Spatie's image library, but it is bundled with MLP and I didn't want to add more deps unnecessarily.
